# PANOSETI PFF to Zarr Conversion Configuration
# HIGH PERFORMANCE PROFILE
# 
# Optimized for:
# - Maximum throughput on BeeGFS/HDD
# - High CPU core utilization (8+ cores)
# - Good compression ratio (blosc-lz4 level 5)
# - Large sequential I/O operations

[pff_to_zarr]

# Compression Settings
# blosc-lz4 is fast and gives good compression
# Level 5 provides a balance: ~2-3x compression with minimal speed impact
codec = "blosc-lz4"
level = 5  # Increased from 1 for better compression (still fast)

# Zarr Chunking
# Larger chunks = better compression and fewer operations
# 65536 frames @ ~2KB/frame = ~128 MB per chunk (optimal for large files)
time_chunk = 65536

# CPU Parallelism
# Maximize core utilization for your 8-core Xeon E5620
num_workers = 24  # Slightly oversubscribed for better CPU saturation
blosc_threads = 16  # Match physical cores for compression

# Async I/O Concurrency
# Higher concurrency keeps I/O busy while CPU compresses
max_concurrent_writes = 16  # Increased for better pipeline utilization

# HDD/BeeGFS Optimization
# Large sequential reads maximize disk throughput
# 150 MB per worker = optimal for BeeGFS stripe utilization
chunk_size_mb = 150

# Notes:
# - This config uses ~1.5-2 GB RAM (10 workers × 150 MB + compression buffers)
# - Expected throughput: 100-300 MB/s on BeeGFS
# - Expected compression: 2-3x (blosc-lz4 level 5)
# - CPU utilization: 700-800% (all 8 cores saturated)

[baseline_subtract]
baseline_window = 100
codec = "blosc-lz4"
level = 5

# Zarr Chunking (can be different from L0 if needed)
# Uncomment and set a value to override input chunks, or leave commented to use input chunks
# time_chunk = 65536

