# PANOSETI PFF to Zarr Conversion Configuration
# MULTI-CLUSTER SUPPORT

[cluster]
# Cluster type: "ssh", "slurm", "local", or leave empty for external
cluster_type = "ssh"  

# External scheduler (takes precedence if provided)
dask_scheduler_address = ""  # e.g., "tcp://10.0.1.2:8786"

# SSH Cluster Configuration
ssh_hosts = ["localhost", "panoseti-dfs0", "panoseti-dfs1", "panoseti-dfs2"]
ssh_workers_per_host = 1
ssh_threads_per_worker = 8
ssh_memory_per_worker = "16GB"

# SLURM Cluster Configuration
slurm_cores = 8
slurm_processes = 1
slurm_memory = "16GB"
slurm_walltime = "01:00:00"
slurm_queue = ""             # Optional
slurm_account = ""           # Optional
slurm_workers = 4

# Local Cluster Configuration
local_n_workers = 4
local_threads_per_worker = 2
local_memory_limit = "auto"

[pff_to_zarr]
use_dask = true
codec = "blosc-lz4"
level = 5
time_chunk = 65536

# Fallback multiprocessing settings
num_workers = 10
blosc_threads = 8
max_concurrent_writes = 16
chunk_size_mb = 150

[baseline_subtract]
use_dask = true
baseline_window = 100
codec = "blosc-lz4"
level = 5
compute_chunk_size = 8192
