# PANOSETI PFF to Zarr Conversion Configuration
# HIGH PERFORMANCE PROFILE WITH DASK DISTRIBUTED COMPUTING
# 
# Optimized for:
# - Multi-node distributed processing via Dask
# - Maximum throughput on BeeGFS/HDD
# - High CPU core utilization across cluster
# - Good compression ratio (blosc-lz4 level 5)

[cluster]
# Dask Cluster Configuration (created once, reused for all operations)
use_dask = true  # Set to false to use local multiprocessing instead

# SSH Cluster Configuration
ssh_hosts = ["localhost", "panoseti-dfs0", "panoseti-dfs1", "panoseti-dfs2"]
ssh_workers_per_host = 1
ssh_threads_per_worker = 16
ssh_memory_per_worker = "16GB"

[pff_to_zarr]
# Compression Settings
codec = "blosc-lz4"
level = 5
time_chunk = 65536

# Local Multiprocessing (used when use_dask = false)
num_workers = 10
blosc_threads = 8
max_concurrent_writes = 16
chunk_size_mb = 150

[baseline_subtract]
baseline_window = 100
codec = "blosc-lz4"
level = 5
compute_chunk_size = 8192
